### ISSUE TITLE
Would you like books added to resources?

### ISSUE THREAD

**Issue by paulbjensen** [jlord/essential-electron#1]
Hi,

There are two books currently in production about Electron, one soon (November this year) and one next summer. Would you be interested in having them listed under the "resources" section? The book links are below:
- https://www.manning.com/books/electron-in-action
- https://www.manning.com/books/cross-platform-desktop-applications

Disclaimer - I'm the author of the 2nd book listed. 

That was a great explanation of Electron's multiple process approach with main and renderer in the site, it makes so easy to understand why Electron's API is designed that way.

**Comment by jlord** [comment]
Hey and thanks!

I'd be up as adding them as resources but would like to wait until they are released.

**Comment by paulbjensen** [comment]
Thanks Jessica, I'll report back once they're published (mine should be available in November, and Steve's is set for sometime in the summer next year).

**Comment by paulbjensen** [comment]
Closing as this is an old issue.
