### ISSUE TITLE
Multiple renderers!

### ISSUE THREAD

**Issue by anaisbetts** [jlord/essential-electron#8]
Hi @jlord! This is super great, I really like it! Thanks for putting in the work to get this to folx. One thing that I noticed might cause confusion is, this notion of "two processes". This is true in the simple case, but really it's, "One renderer for every window you create" (and really really, one renderer for every window and `webview` tag you create).

It might be better to say, two _types_ of processes, then really drive home the point that every Window gets its own process - "one window == one process" is pretty straightforward for people to understand I think, and maybe beef up the "Think of it like this" section a bit

**Comment by jlord** [comment]
Yeah, I was trying to make that distinction but I think it can be more clear, especially by explicitly saying _types_ of processes 👍 Incoming edits 🔜
